### ISSUE TITLE
Need some help with building FW-RNN cell

### ISSUE THREAD

**Issue by ion-elgreco** [jxwufan/AssociativeRetrieval#3]
Hi @jxwufan,

I am trying to build the same fw-rnn cell from the paper 'Using Fast Weights to Attend to the Recent Past', but I am using Tensorflow 2.4. 

But my implementation sadly returns an error, perhaps you can see what I am doing wrong? I am pretty new to tensorflow, at least to model subclassing, so I do not really understand what is going wrong. Here is a link to my code, error, and model summary:

https://gist.github.com/ion-elgreco/cc6fed29a4f6fb6813b71d5e7e8f2c87

The error code gives this:
`TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: FW-RNN/while/fw_rnn_cell_2/add_2:0`

I hope you can help me with this since you have successfully implemented this before!

**Comment by jxwufan** [comment]
Hi @ion-elgreco ,
Unfortunately, I quit deep learning for more than 3 years so I don't really know the current TensorFlow. But I believe the API changes are minor, I suggest you go through the whole official TensorFlow tutorials and hopefully you will figure it out.

**Comment by ion-elgreco** [comment]
> Hi @ion-elgreco ,
> Unfortunately, I have quitted deep learning for more than 3 years so I don't really know the current TensorFlow. But I believe the API changes are minor, I suggest you go through the whole official TensorFlow tutorials and hopefully you will figure it out.

Ah that's a pity to hear. I could not find much information regarding this TypError sadly. Thank you for the fast response! 💯
